# Generated by Django 4.0.6 on 2023-09-03 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FFIapp', '0002_customer_marina_newspost_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='Note',
            field=models.TextField(default='No notes.', max_length=500),
        ),
        migrations.AddField(
            model_name='boat',
            name='Name',
            field=models.CharField(default='Boat', max_length=50),
        ),
        migrations.AddField(
            model_name='boat',
            name='Note',
            field=models.TextField(default='No notes.', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='City',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='customer',
            name='Contact_Info',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='Note',
            field=models.TextField(default='No notes.', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='Street',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='Zip',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Note',
            field=models.TextField(default='No notes.', max_length=500),
        ),
        migrations.AddField(
            model_name='marina',
            name='Note',
            field=models.TextField(default='No notes.', max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='First_Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Last_Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='Region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FFIapp.region'),
        ),
    ]
