# Generated by Django 4.0.6 on 2022-08-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FFIapp', '0002_alter_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank='yes', max_length=20, null='yes'),
            preserve_default='yes',
        ),
    ]
