# Generated by Django 4.0.6 on 2023-09-03 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FFIapp', '0003_region_appointment_note_boat_name_boat_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FFIapp.employee'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Slip',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Zinc_Service_Units',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
