# Generated by Django 4.0.6 on 2023-09-03 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FFIapp', '0004_alter_appointment_employee_alter_appointment_slip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Date_Of_Appointment',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Note',
            field=models.TextField(default='No notes.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='Note',
            field=models.TextField(default='No notes.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FFIapp.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='City',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Contact_Info',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Note',
            field=models.TextField(default='No notes.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Street',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Can_Do',
            field=models.ManyToManyField(null=True, to='FFIapp.service'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Note',
            field=models.TextField(default='No notes.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='marina',
            name='City',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='marina',
            name='Note',
            field=models.TextField(default='No notes.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='marina',
            name='Street',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marina',
            name='Zip',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
