# Generated by Django 4.0.6 on 2022-08-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FFIapp', '0004_newspost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='newspost',
            name='message',
            field=models.TextField(max_length=5000),
        ),
    ]
