# Generated by Django 4.0.6 on 2022-08-12 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FFIapp', '0005_alter_newspost_options_alter_newspost_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={},
        ),
    ]
