# Generated by Django 4.0.6 on 2023-09-03 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FFIapp', '0005_alter_appointment_date_of_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Date_Of_Appointment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FFIapp.employee'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Note',
            field=models.TextField(blank=True, default='No notes.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Slip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Zinc_Service_Units',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='Note',
            field=models.TextField(blank=True, default='No notes.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FFIapp.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='City',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Contact_Info',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='First_Name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Note',
            field=models.TextField(blank=True, default='No notes.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Street',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Zip',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Can_Do',
            field=models.ManyToManyField(blank=True, null=True, to='FFIapp.service'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Note',
            field=models.TextField(blank=True, default='No notes.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='marina',
            name='City',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='marina',
            name='Note',
            field=models.TextField(blank=True, default='No notes.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='marina',
            name='Region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FFIapp.region'),
        ),
        migrations.AlterField(
            model_name='marina',
            name='Street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marina',
            name='Zip',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
