# Generated by Django 4.0.6 on 2023-09-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FFIapp', '0006_alter_appointment_date_of_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='boat_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zinc_Count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Can_Do',
        ),
        migrations.AddField(
            model_name='employee',
            name='Status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='Entry_Instructions',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='Base_Price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='Unit_Price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
