# Generated by Django 4.0.6 on 2022-08-12 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FFIapp', '0006_alter_newspost_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspost',
            old_name='author',
            new_name='user',
        ),
    ]
