# Generated by Django 4.0.6 on 2022-08-13 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FFIapp', '0007_rename_author_newspost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='user',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank='yes', max_length=50, null='no'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank='yes', max_length=100, null='no'),
        ),
    ]
