# Generated by Django 4.0.6 on 2022-08-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FFIapp', '0008_alter_newspost_user_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='user',
        ),
        migrations.AddField(
            model_name='newspost',
            name='author',
            field=models.TextField(default='Unknown', max_length=500),
        ),
    ]
