# Generated by Django 4.0.6 on 2023-09-03 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FFIapp', '0009_remove_newspost_user_newspost_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marinas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Street', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=25)),
                ('Zip', models.PositiveSmallIntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=3000)),
                ('Unit_Price', models.PositiveSmallIntegerField(max_length=8)),
                ('Unit_Price_Description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='newspost',
            name='author',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='message',
            field=models.TextField(max_length=50000),
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Can_Do', models.ManyToManyField(to='FFIapp.services')),
            ],
        ),
        migrations.CreateModel(
            name='Boats',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Size', models.PositiveSmallIntegerField(max_length=4)),
                ('Preferred_Interval', models.PositiveSmallIntegerField(max_length=3)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FFIapp.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Date_Submitted', models.DateField(auto_now_add=True)),
                ('Date_Of_Appointment', models.DateField()),
                ('Slip', models.CharField(max_length=15)),
                ('Clean_Service', models.BooleanField(default=True)),
                ('Zinc_Service', models.BooleanField(default=False)),
                ('Zinc_Service_Units', models.PositiveSmallIntegerField(max_length=4)),
                ('Boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FFIapp.boats')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FFIapp.employees')),
                ('Marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FFIapp.marinas')),
            ],
        ),
    ]
