# Generated by Django 4.0.6 on 2023-09-03 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FFIapp', '0009_remove_newspost_user_newspost_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marina',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Street', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=25)),
                ('Zip', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=3000)),
                ('Unit_Price', models.PositiveSmallIntegerField()),
                ('Unit_Price_Description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='newspost',
            name='author',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='message',
            field=models.TextField(max_length=50000),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Can_Do', models.ManyToManyField(to='FFIapp.service')),
            ],
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Size', models.PositiveSmallIntegerField()),
                ('Preferred_Interval', models.PositiveSmallIntegerField()),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FFIapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Date_Submitted', models.DateField(auto_now_add=True)),
                ('Date_Of_Appointment', models.DateField()),
                ('Slip', models.CharField(max_length=15)),
                ('Clean_Service', models.BooleanField(default=True)),
                ('Zinc_Service', models.BooleanField(default=False)),
                ('Zinc_Service_Units', models.PositiveSmallIntegerField()),
                ('Boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FFIapp.boat')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FFIapp.employee')),
                ('Marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FFIapp.marina')),
            ],
        ),
    ]
