# Generated by Django 4.0.6 on 2023-09-03 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FFIapp', '0010_customers_marinas_services_alter_newspost_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Size', models.PositiveSmallIntegerField()),
                ('Preferred_Interval', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=3000)),
                ('Unit_Price', models.PositiveSmallIntegerField()),
                ('Unit_Price_Description', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Marinas',
            new_name='Marina',
        ),
        migrations.RemoveField(
            model_name='boats',
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Zinc_Service_Units',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.AddField(
            model_name='boat',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FFIapp.customer'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FFIapp.boat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Can_Do',
            field=models.ManyToManyField(to='FFIapp.service'),
        ),
        migrations.DeleteModel(
            name='Boats',
        ),
    ]
