# Generated by Django 4.0.6 on 2023-09-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FFIapp', '0011_boat_service_rename_marinas_marina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marina',
            name='Zip',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
